var hazards = 
[
    "Slightly Cold",
    "Massive Snakes",
    "inanimate objects go on adventures when noone is looking",
    "Crazy Crustaceans",
    "Radioactive",
    "Smells Of Cheese",
    "Covered in Lego Blocks",
    "Ruled by a Mad King",
    "Below Freezing temperatures",
    "Perfect...a little to perfect",
    "To much Attitude",
    "Giggling parasites" ,
    "Xenomorphs",
    "Screaming rocks",
    "Large flying creatures",
    "Vin Diesel",
    "Actually flat",
    "Smells of cabbage", 
    "Everything Retorts With One Liners",
    "Made out of peanuts", 
    "Under construction",
    "Boring",
    "Ironic" ,
    "Filled with creatures that could either be Kurt Russel or Keithe David",
    "Creatures say there names",
    "Deadly to humans and safe for robots",
    "Everything sings",
    "Everything sighs",
    "Slightly smaller on the right",
    "Removed from the archives",
    "God complex",
    "Not the 3rd planet from the sun",
    "Wasn't featured in galaxy quest",
    "Part of the alliance" ,
    "Is actually Kurt Russell" ,
    "Everything",
    "Nothing",
    "Too Hot",
    "Too Cold",
    "Too good",
    "Replicant's Colony",
    "Not Siutable for Children Under 3",
    "Isnt Gluten Free",
    "Plot Twist, Its Actually Earth",
    "Filled with Creatures that Blew it up...those manaics!!!",
    "Scorching Heat",
    "Runaway GreenHouse Effect",
]